### ISSUE TITLE
Add wildcard ignore

### ISSUE THREAD

**Issue by voxpelli** [maxogden/dependency-check#92] opened 2018-06-25 12:51 UTC
Eg. ESLint modules are not used through ordinary `require()`:s and thus show up as unused.

To be able to do something like `dependency-check -i eslint-*` would be pretty neat.

**Comment by blakeembrey** [comment] 2018-09-12 03:27
Closing as a duplicate of https://github.com/maxogden/dependency-check/issues/65. I'll update its description to have wildcard in case that's the reason it couldn't be found.

**Closed by blakeembrey** 2018-09-12 03:27 UTC
Labels: enhancement
