### ISSUE TITLE
Unexpected token with acorn

### ISSUE THREAD

**Issue by RichardLitt** [maxogden/dependency-check#29] opened 2015-05-18 07:31 UTC
Trying to run this, and I get this result. I opened this issue [here](https://github.com/marijnh/acorn/issues/260), but it doesn't seem to be an issue with acorn, but rather with how we're doing our error reporting. Thoughts? 

``` js
$ dependency-check .
/Users/richard/.nvm/versions/node/v0.12.0/lib/node_modules/dependency-check/node_modules/detective/node_modules/acorn/dist/acorn.js:1044
  throw err;
        ^
SyntaxError: Unexpected token (26:3)
    at Parser.pp.raise (/Users/richard/.nvm/versions/node/v0.12.0/lib/node_modules/dependency-check/node_modules/detective/node_modules/acorn/dist/acorn.js:1042:13)
    at Parser.pp.unexpected (/Users/richard/.nvm/versions/node/v0.12.0/lib/node_modules/dependency-check/node_modules/detective/node_modules/acorn/dist/acorn.js:1534:8)
    at Parser.pp.parseExprAtom (/Users/richard/.nvm/versions/node/v0.12.0/lib/node_modules/dependency-check/node_modules/detective/node_modules/acorn/dist/acorn.js:440:12)
    at Parser.pp.parseExprSubscripts (/Users/richard/.nvm/versions/node/v0.12.0/lib/node_modules/dependency-check/node_modules/detective/node_modules/acorn/dist/acorn.js:331:19)
    at Parser.pp.parseMaybeUnary (/Users/richard/.nvm/versions/node/v0.12.0/lib/node_modules/dependency-check/node_modules/detective/node_modules/acorn/dist/acorn.js:312:19)
    at Parser.pp.parseExprOps (/Users/richard/.nvm/versions/node/v0.12.0/lib/node_modules/dependency-check/node_modules/detective/node_modules/acorn/dist/acorn.js:266:19)
    at Parser.pp.parseMaybeConditional (/Users/richard/.nvm/versions/node/v0.12.0/lib/node_modules/dependency-check/node_modules/detective/node_modules/acorn/dist/acorn.js:248:19)
    at Parser.pp.parseMaybeAssign (/Users/richard/.nvm/versions/node/v0.12.0/lib/node_modules/dependency-check/node_modules/detective/node_modules/acorn/dist/acorn.js:226:19)
    at Parser.pp.parseParenAndDistinguishExpression (/Users/richard/.nvm/versions/node/v0.12.0/lib/node_modules/dependency-check/node_modules/detective/node_modules/acorn/dist/acorn.js:487:28)
    at Parser.pp.parseExprAtom (/Users/richard/.nvm/versions/node/v0.12.0/lib/node_modules/dependency-check/node_modules/detective/node_modules/acorn/dist/acorn.js:410:19)
```

**Comment by voxpelli** [comment] 2015-05-18 07:48
So the error here is the same as #16, right? But good advice from the acorn-people on how to get closer to solving it:

> It looks like dependency-check is just running against a folder but not reporting filename where error occurs - so better to raise issue on their repo so that they could add better reporting.

We should totally try to do that. Would probably have to be done as a patch towards [node-detective](https://github.com/substack/node-detective) though, but we can keep this open to track it.

**Comment by RichardLitt** [comment] 2015-05-18 08:23
Ah. Looks like the same, yeah. I knew I filed this before, but couldn't find it.

**Comment by voxpelli** [comment] 2017-01-29 19:24
Closing this as a duplicate of #16, which I also just closed because parsers are now pluggable as of the merging of #61, which means that alternative parsers that supports all of the syntaxes one use can now be plugged in.

**Closed by voxpelli** 2017-01-29 19:24 UTC
