### ISSUE TITLE
alternate entry points now require a separate package.json file

### ISSUE THREAD

**Issue by yoshuawuyts** [maxogden/dependency-check#73] opened 2017-07-02 00:50 UTC
Given the following scenario:
```txt
index.js
package.json
bin/
  index.js
```
It now appears that this module incorrectly assumes `bin/package.json` should exist. Instead it should rely on `package.json` in the root dir.

Encountered this error:
```txt

> bankai@8.1.1 deps /Users/anon/src/yoshuawuyts/bankai
> dependency-check . && dependency-check . --extra --no-dev

Cannot find module '/Users/anon/src/yoshuawuyts/bankai/bin/package.json' from
'/Users/anon/src/yoshuawuyts/bankai/bin'

npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/anon/.nvm/versions/node/v6.4.0/bin/node" "/Users/anon/.n
vm/versions/node/v6.4.0/bin/npm" "run" "deps"
npm ERR! node v6.4.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! bankai@8.1.1 deps: `dependency-check . && dependency-check . --extra
--no-dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bankai@8.1.1 deps script 'dependency-check . && depende
ncy-check . --extra --no-dev'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bankai package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     dependency-check . && dependency-check . --extra --no-dev
npm ERR! You can get information on how to open an issue for this project with
:
npm ERR!     npm bugs bankai
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bankai
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/anon/src/yoshuawuyts/bankai/npm-debug.log
npm ERR! Test failed.  See above for more details.

```

**Comment by yoshuawuyts** [comment] 2017-07-02 00:51
This was introduced between patch `>2.6.0` and `<=2.9.1`

**Comment by blakeembrey** [comment] 2017-07-02 01:34
This specific error is coming from `resolve` (specifically https://github.com/substack/node-resolve/blob/452fdf981330f96d7fef88805b24e40ea24a89e1/lib/async.js#L48), so something isn't resolving as expected - seems like it's failing on `index.js` and falling back to `package.json` to follow node module resolution. I'll take a look and see if I notice anything odd.

**Comment by blakeembrey** [comment] 2017-07-02 01:37
I can't replicate it after cloning your project. Can you let me know what version you're using?

![image](https://user-images.githubusercontent.com/1088987/27766645-813165d2-5ea5-11e7-9a94-7711344a0160.png)

**Comment by blakeembrey** [comment] 2017-07-29 05:59
Closing this now as there's been no response. Feel free to follow up if it's still an issue 😄

**Comment by yoshuawuyts** [comment] 2017-07-29 09:55
Ohey, I totes missed your reply. Im on holiday right now, but this
consistently keeps failing for me across projects. If you could keep this
issue open that'd be grand. Thanks!

**Comment by voxpelli** [comment] 2018-12-25 16:47
@yoshuawuyts Any update on this from your end? If so, just mention me and I'll open this up again. Would be great to know if the problem persist in the latest version, and since Blake couldn't reproduce this it would be hard for any of us to verify.

**Closed by voxpelli** 2018-12-25 16:47 UTC
